// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZV-kec-TZlaTMr5MHZDiTph_caTzMTXg',
    appId: '1:524881463867:android:78362cac50ca5e0e176a1e',
    messagingSenderId: '524881463867',
    projectId: 'uninotice-2e07c',
    storageBucket: 'uninotice-2e07c.firebasestorage.app',
    databaseURL: 'https://uninotice-2e07c-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmuY4Byzxf9AU7Ig2LyI5v3t-FzqkS3c8',
    appId: '1:524881463867:web:803bcbcc35e179b9176a1e',
    messagingSenderId: '524881463867',
    projectId: 'uninotice-2e07c',
    authDomain: 'uninotice-2e07c.firebaseapp.com',
    storageBucket: 'uninotice-2e07c.firebasestorage.app',
    measurementId: 'G-KN2MCHKHNP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAEY-n_PH93rvrpGD5fzXL_iGvTJyBkSE',
    appId: '1:524881463867:ios:bbf8edc73c6874f7176a1e',
    messagingSenderId: '524881463867',
    projectId: 'uninotice-2e07c',
    storageBucket: 'uninotice-2e07c.firebasestorage.app',
    iosClientId: '524881463867-34grkde7sqbqk9lbobccg42epkrbm9s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAEY-n_PH93rvrpGD5fzXL_iGvTJyBkSE',
    appId: '1:524881463867:ios:bbf8edc73c6874f7176a1e',
    messagingSenderId: '524881463867',
    projectId: 'uninotice-2e07c',
    storageBucket: 'uninotice-2e07c.firebasestorage.app',
    iosClientId: '524881463867-34grkde7sqbqk9lbobccg42epkrbm9s2.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmuY4Byzxf9AU7Ig2LyI5v3t-FzqkS3c8',
    appId: '1:524881463867:web:2657b2c601656be9176a1e',
    messagingSenderId: '524881463867',
    projectId: 'uninotice-2e07c',
    authDomain: 'uninotice-2e07c.firebaseapp.com',
    storageBucket: 'uninotice-2e07c.firebasestorage.app',
    measurementId: 'G-WJEP04BMJL',
  );

}